--- #YAML:1.0
name:               Devel-PartialDump
version:            0.13
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Moose:             0
    namespace::clean:  0.08
    Scalar::Util:      0
    Sub::Exporter:     0
    Test::use::ok:     0
    Test::Warn:        0.21
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
