--- #YAML:1.0
name:                Devel-PartialDump
version:             0.05
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Mouse:                         0
    namespace::clean:              0.08
    Scalar::Util:                  0
    Sub::Exporter:                 0
    Test::use::ok:                 0
    Test::Warn:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
