use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006001
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
יובל
קוג
Yuval
Kogman
nothingmuch
David
Golden
dagolden
Florian
Ragwitz
rafl
Jesse
Luehrs
doy
Karen
Etheridge
ether
Leo
Lapworth
web
lib
Devel
PartialDump
